Repository DiegoTorresP/KiwiSazon, pull requests merged in 2023-06, with the labels that each got.

#1 V1 - Esqueleto
  app.js
  bin/www
  package.json
  public/stylesheets/style.css
  routes/index.js
  routes/users.js
  views/error.ejs
  views/index.ejs
Labels: question

#2 Cambios V1.1 - Complementos de carpetas
  .gitignore
  app.js
  package-lock.json
  package.json
Labels: question

#4 Conexión a base de datos
  app.js
  config/DBConnection.js
  config/dbConfig.js
Labels: New feature

#5 Update .gitignore
  .gitignore
Labels: bug

#6 Primer carga a rama Main
  README.md
Labels: bug

#7 Primera carga a main.
  .gitignore
  README.md
  app.js
  bin/www
  config/DBConnection.js
  config/dbConfig.js
  package-lock.json
  package.json
  public/stylesheets/style.css
  routes/index.js
  routes/users.js
  views/error.ejs
  views/index.ejs
Labels: New feature
