Repository DiegoTorresP/KiwiSazon, pull requests merged in 2023-08, with the labels that each got.

#19 Compartir Recetas y Diseño
  controllers/receta.js
  routes/users.js
  views/Recipes/detalleReceta.ejs
  views/home/index.ejs
  views/partials/nav.ejs
  views/user/misrecetas.ejs
  views/user/recetasFavoritas.ejs
Labels: New feature

#20 ajustes a valoraciones
  controllers/receta.js
Labels: bug

#22 Ajustes por Pruebas
  README.md
Labels: fix

#25 Correcciones ortográficas
  uploads/receta/2023-08-18T14-36-36.387ZCHILES-EN-NOGADA.jpg
  uploads/receta/2023-08-18T14-36-42.558ZCHILES-EN-NOGADA.jpg
  uploads/receta/2023-08-18T14-42-20.970Ztinga de pollo.jpeg
  uploads/receta/2023-08-18T14-45-46.573ZPaletas de Tres Leches con Fruta.jpeg
  uploads/receta/2023-08-18T14-49-36.332ZTacos de lechuga con pescado.jpeg
  views/Recipes/allRecipes.ejs
  views/Recipes/detalleReceta.ejs
  views/admin/adminCategorias.ejs
  views/admin/adminHome.ejs
  views/admin/adminRecetas.ejs
  views/auth/login.ejs
  views/auth/registro.ejs
  views/home/index.ejs
  views/partials/footer.ejs
  views/partials/nav.ejs
  views/user/misrecetas.ejs
  views/user/recetasFavoritas.ejs
Labels: fix

#26 Corrección de título en vista de detalle.
  views/Recipes/detalleReceta.ejs
Labels: fix
